### ISSUE TITLE
Why are we adding the Input suffix to proto input messages?

### ISSUE THREAD

**Issue by toctan** [danielvladco/go-proto-gql#18]
I'm just curious why the suffix is added here:
https://github.com/danielvladco/go-proto-gql/blob/master/plugin/plugin.go#L625

What's the benefit? It seems like we could just use gqlgen's autobind to bind these input messages to generated protobuf models automatically without the suffix, but now we need to use `gqlgencfg_out` plugin to generate extra yaml configs for these input messages.

**Comment by danielvladco** [comment]
Hello, sorry for late reply. I've been working on a big refactor for this library.

We need to add that suffix because if a message is used both for input and output, we need to generate an graphql object for output and an input object for input. This means that these two type names will overlap and the generated schema will have errors.

After this refactor you shouldn't have any problems using autobind. I actually deleted the third plugin that generates yaml configuration in favour of using autobind. Also `gogql` plugin will generate aliases for those inputs and the suffix is no longer a problem.
