### ISSUE TITLE
Add support for maps rather than using a scalar as a workaround

### ISSUE THREAD

**Issue by vtolstov** [danielvladco/go-proto-gql#4]
how to avoid this piece of code?
```
if err != nil {          
  panic("stupid map")    
}                        
```

**Comment by danielvladco** [comment]
Hi,

Sorry at the moment maps are not supported due to limitations of the graphQL. I added this stupid implementation as a quick solution to the problem...

I would try to avoid using maps with graphql if possible. 

https://github.com/99designs/gqlgen/issues/663 If this issue of gqlgen  will be fixed I will be able to implement a map as a list of map entries and generate resolvers that translate the list into a go map.

**Comment by vtolstov** [comment]
thanks for info, i'm subscribe to gqlgen to check this issue

**Comment by danielvladco** [comment]
If I manage to merge this PR, the issue will be pretty much fixed https://github.com/99designs/gqlgen/pull/1404

**Comment by danielvladco** [comment]
Added map support as an array of entry types. 
Check for example:
https://github.com/danielvladco/go-proto-gql/blob/master/example/codegen/pb/constructs.graphqls#L281-L284
https://github.com/danielvladco/go-proto-gql/blob/master/example/codegen/pb/constructs.graphqls#L273

However if you wish to generate go-lang bindings as well, instead of using the official `github.com/99designs/gqlgen` generator you will need to use this fork `github.com/danielvladco/gqlgen`
